-- Add patient_specific_configs table if it doesn't exist yet
CREATE TABLE IF NOT EXISTS patient_specific_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procedure_id BIGINT NOT NULL REFERENCES procedures(id) ON DELETE CASCADE,
    phase_id BIGINT NOT NULL REFERENCES phases(id) ON DELETE CASCADE,
    patient_type_id BIGINT NOT NULL REFERENCES patient_types(id) ON DELETE CASCADE,
    config JSONB,  -- Stores the specific configuration for this combination
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(procedure_id, phase_id, patient_type_id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS patient_specific_configs_procedure_id_idx ON patient_specific_configs (procedure_id);
CREATE INDEX IF NOT EXISTS patient_specific_configs_phase_id_idx ON patient_specific_configs (phase_id);
CREATE INDEX IF NOT EXISTS patient_specific_configs_patient_type_id_idx ON patient_specific_configs (patient_type_id);

-- Enable RLS and create policy
ALTER TABLE patient_specific_configs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    BEGIN
        CREATE POLICY "Allow public access to patient_specific_configs" ON patient_specific_configs
            FOR ALL USING (true) WITH CHECK (true);
    EXCEPTION WHEN others THEN
        RAISE NOTICE 'Policy already exists, skipping creation';
    END;
END
$$; 